[package]
name = "store"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
diesel = { version = "2.3.2", features = ["postgres", "chrono"] }
dotenvy = "0.15.7"
uuid = { version = "1.18.1", features = [ "v4" ] }
argon2 = "0.5.3"
rand = "0.8"
